version: '3.1'

services:

  couchbase:
    image: couchbase
    container_name: PokemonDB
    deploy:
      replicas: 1
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
